name: team-09-sperrins

on:
  pull_request:
    branches:
      - main


jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    # implement make file execution
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      #Set up python
      - name: use-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"
      - name: Run all checks
        run: make all

  deploy-lambda:
    name: deploy-lambda
    runs-on: ubuntu-latest
    needs: run-tests
    environment: dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        #Install terraform
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup AWS cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # terraform init
      - name: Terraform init 
        working-directory: terraform
        run: terraform init
      # terraform plan
      - name: Terraform plan 
        working-directory: terraform
        run: terraform plan -var="email_address=${{ secrets.EMAIL_SUBSCRIBED_TO_SNS }}"
      # terraform fmt
      - name: Terraform format
        working-directory: terraform
        run: terraform fmt
      - name: Terraform apply -var="email_address=${{ secrets.EMAIL_SUBSCRIBED_TO_SNS }}"
        working-directory: terraform 
        run: terraform apply -auto-approve